import { chromium } from "playwright";
const [,, route="/", w="390", h="844", label="shot"] = process.argv;
const b = await chromium.launch({executablePath:"/usr/local/bin/chrome", args:["--no-sandbox","--disable-dev-shm-usage"]});
const p = await b.newPage({viewport:{width:+w,height:+h}});
await p.goto("http://127.0.0.1:4321"+(route==="/"?"/":route+"/"),{waitUntil:"networkidle"});
await p.evaluate(()=>document.fonts.ready);
await p.evaluate(async()=>{document.documentElement.style.scrollBehavior="auto";const s=innerHeight*0.7;for(let y=0;y<document.body.scrollHeight;y+=s){scrollTo(0,y);await new Promise(r=>setTimeout(r,110));}scrollTo(0,0);await new Promise(r=>setTimeout(r,400));});
await p.waitForTimeout(600);
await p.screenshot({path:`scripts/review/${label}.png`, fullPage:true});
console.log("ok", label);
await b.close();
